server:
  port: 8001

spring:
  application:
    name: payment-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
    register-with-eureka: true  # 注册到eureka,不注册自己
    fetch-registry: true  # 注册中心不拉取服务注册信息