server:
  port: 9081

spring:
  application:
    name: nacos-payment-consumer
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

service-url:
  nacos-user-service: http://nacos-payment-provider