server:
  port: 80

spring:
  application:
    name: order-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka
    register-with-eureka: true  # 注册到eureka,不注册自己
    fetch-registry: true  # 注册中心不拉取服务注册信息