server:
  port: 9527

spring:
  application:
    name: server-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启服务发现
      routes:
      - id: payment_route1 # 不要求规则，但必唯一
        uri: http://localhost:8001
        predicates:
          - Path=/payment/get/**
          - After=2023-11-21T12:00:00.000+08:00[Asia/Shanghai]
        filters:
          - AddRequestParameter=red, blue

      - id: payment_route2 # 不要求规则，但必唯一
        uri: get://PAYMENT-SERVICE
        predicates:
          - Path=/payment/create/**
#          - Cookie=username,zmy


eureka:
  instance:
    hostname: service-gateway
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
    register-with-eureka: true  # 注册到eureka,不注册自己
    fetch-registry: true  # 注册中心不拉取服务注册信息