server:
  port: 7001

eureka:
  instance:
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7002/eureka/
    register-with-eureka: false  # 注册到eureka,不注册自己
    fetch-registry: false  # 注册中心不拉取服务注册信息